<a href="https://colab.research.google.com/github/p-tech/dm-2026/blob/main/maths/Aggregations_in_Dataframes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Common aggregation functions:**

In [1]:
import pandas as pd

df = pd.DataFrame({
    "department": ["Sales", "Sales", "Tech", "Tech"],
    "employee": ["A", "B", "C", "D"],
    "salary": [40000, 50000, 60000, 70000],
    "sales": [10, 15, 8, 20]
})

Aggregate a whole column:

In [2]:
df["salary"].sum()
df["salary"].mean()
df["salary"].median()
df["salary"].min()
df["salary"].max()
df["salary"].count()
df["salary"].std()

12909.944487358056

Will only show the last expression.

In [3]:
df["salary"].agg(["sum", "mean", "median", "min", "max", "count", "std"])

sum       220000.000000
mean       55000.000000
median     55000.000000
min        40000.000000
max        70000.000000
count          4.000000
std        12909.944487
Name: salary, dtype: float64

Similar to SQL - we can aggregate based on groups.

In [5]:
df.groupby("department")["salary"].agg(["count", "sum", "mean", "min", "max"])

            count     sum     mean    min    max          std
department
Sales           2   90000  45000.0  40000  50000  7071.067812
Tech            2  130000  65000.0  60000  70000  7071.067812

Carry out different calculations to each column in the same groupby

In [9]:
df.groupby("department").agg(
    total_salary=("salary", "sum"),
    average_salary=("salary", "mean"),
    total_sales=("sales", "sum"),
    max_sales=("sales", "max")
)

            total_salary  average_salary  total_sales  max_sales
department
Sales              90000         45000.0           25         15
Tech              130000         65000.0           28         20

Custom aggregations

In [10]:
df.groupby("department").agg(
    salary_range=("salary", lambda x: x.max() - x.min())
)

            salary_range
department
Sales              10000
Tech               10000

Lamda is a small function without having to declare one explicity in the code, using a def.

In [11]:
def salary_range(x):
    return x.max() - x.min()

df.groupby("department").agg(
    salary_range=("salary", salary_range)
)

            salary_range
department
Sales              10000
Tech               10000